// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNa486YRCN7U25AQU52OcXTTwwNKzr6A',
    appId: '1:345727668315:web:012e2c0ad4843a5f54ef7e',
    messagingSenderId: '345727668315',
    projectId: 'chat-app-992dd',
    authDomain: 'chat-app-992dd.firebaseapp.com',
    storageBucket: 'chat-app-992dd.appspot.com',
    measurementId: 'G-CBCFEB46FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnsvtBrBiUYib0eFoIIXxj8OmsZVuVmo',
    appId: '1:345727668315:android:0f2fbe97b410de6e54ef7e',
    messagingSenderId: '345727668315',
    projectId: 'chat-app-992dd',
    storageBucket: 'chat-app-992dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKmARQAqhiWMTqz0XsMKR2N5BnfmMv2Q',
    appId: '1:345727668315:ios:8c9e74eb1d48439954ef7e',
    messagingSenderId: '345727668315',
    projectId: 'chat-app-992dd',
    storageBucket: 'chat-app-992dd.appspot.com',
    iosClientId: '345727668315-j3voevajm00l2u32cua31ikcjhpseoh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKmARQAqhiWMTqz0XsMKR2N5BnfmMv2Q',
    appId: '1:345727668315:ios:8c9e74eb1d48439954ef7e',
    messagingSenderId: '345727668315',
    projectId: 'chat-app-992dd',
    storageBucket: 'chat-app-992dd.appspot.com',
    iosClientId: '345727668315-j3voevajm00l2u32cua31ikcjhpseoh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
